Repository cloudflare/workers-docs, pull requests merged in 2019-11, with the labels that each got.

#503 Staging with big fluff
  content/tooling/wrangler/commands.md
  static/css/main.css
  wrangler.toml
Labels: needs review

#512 Data Loss Prevention Snippet
  content/templates/snippets/private_data_loss.md
  data/snippet/modify_req_props.toml
  data/snippet/private_data_loss.toml
  data/snippet/send_raw_html.toml
Labels: needs review, template gallery

#517 Change wording of old concepts sections
  content/index.md
  content/quickstart/_index.md
Labels: needs review

#515 Template Pages 🎨
  content/templates/media/external-link.svg
  content/templates/media/left-arrow.svg
  content/templates/snippets/ab_testing.md
  layouts/_default/baseof.html
  layouts/partials/template_page.html
  layouts/shortcodes/template-page.html
  static/css/code.css
  static/css/template.css
  static/js/workers.js
  static/svg/copy-box.svg
Labels: needs review

#521 Move staging to bigfluff
  config-staging.toml
Labels: tech

#530 Formatting fixes
  content/templates/boilerplates/router.md
  layouts/partials/template_page.html
  static/css/template.css
Labels: needs review

#532 Update Wrangler assets
  content/tooling/wrangler/_index.md
  content/tooling/wrangler/media/banner.png
  content/tooling/wrangler/media/wrangler-demo.gif
Labels: enhancement

#543 Edit on Github button
  layouts/_default/li.html
  layouts/_default/list.html
  layouts/_default/single.html
  static/css/main.css
  static/js/templates.js
  static/svg/github.svg
Labels: needs review

#545 Fix demo ordering
  layouts/partials/boilerplate.html
  layouts/partials/snippet.html
Labels: needs review

#540 Update env var docs
  content/quickstart/_index.md
  content/tooling/api/requests.md
  content/tooling/wrangler/commands.md
  content/tooling/wrangler/configuration/_index.md
Labels: needs review

#546 Github links to template pages
  content/templates/pages/sites.md
  layouts/partials/template-page.html
  static/css/template.css
Labels: needs review

#551 Updates KV documentation with latest screenshots
  content/reference/media/bind-namespace.png
  content/reference/media/create-namespace.png
  content/reference/media/resources-namespaces.png
  content/reference/storage/overview.md
  content/reference/storage/reading-data.md
  content/tutorials/build-a-serverless-function/_index.md
Labels: kv, needs review, reference

#547 Remove old archive recipe and 301 it to sites
  content/archive/recipes/static-site.md
  workers-site/redirects/oldDocs.js
Labels: needs review
