Repository cloudflare/workers-docs, pull requests merged in 2019-10, with the labels that each got.

#404 Add hot-link protection snippet.
  content/templates/snippets/hotlink-protection.md
  data/snippet/hot_link_protection.toml
  workers-site/redirects/oldDocs.js
Labels: template gallery

#403 Add bulk origin proxies snippet.
  content/templates/snippets/bulk_origin_proxies.md
  data/snippet/bulk_origin_proxies.toml
Labels: template gallery

#387 Signed requests snippet
  content/templates/snippets/signed_request.md
  data/snippet/auth_with_headers.toml
  data/snippet/bulk_origin_proxies.toml
  data/snippet/signed_request.toml
  workers-site/redirects/oldDocs.js
  workers-site/src/main.js
Labels: template gallery

#452 Add template IDs
  data/snippet/ab_testing.toml
  data/snippet/alter_headers.toml
  data/snippet/conditional_response.toml
  data/snippet/debugging.toml
  data/snippet/hot_link_protection.toml
  data/snippet/http2_push.toml
  data/snippet/tls_version.toml
Labels: needs review, template gallery

#462 Fix search from showing sections with no results
  static/js/templates.js
Labels: needs review

#463 Cookie extract template
  content/templates/snippets/cookie_extract.md
  data/snippet/cookie_extract.toml
Labels: needs review

#465 Remove random underscores
  content/reference/apis/fetch-event.md
Labels: needs review

#485 Wrangler docs from github
  content/about/_index.md
  content/quickstart/_index.md
  content/reference/_index.md
  content/sites/_index.md
  content/sites/ignore-assets.md
  content/templates/_index.md
  content/tooling/_index.md
  content/tooling/wrangler.md
  content/tooling/wrangler/_index.md
  content/tooling/wrangler/commands.md
  content/tooling/wrangler/configuration/_index.md
  content/tooling/wrangler/configuration/environments.md
  content/tooling/wrangler/install.md
  content/tooling/wrangler/kv_commands.md
  content/tooling/wrangler/media/banner.png
  content/tooling/wrangler/media/wrangler-demo.gif
  content/tooling/wrangler/sites.md
  content/tooling/wrangler/webpack.md
  content/tutorials/_index.md
  layouts/partials/navigation.html
  workers-site/redirects/newDocs.js
Labels: needs review
