Repository cloudflare/workers-docs, pull requests merged in 2020-05, with the labels that each got.

#769 update readme node version
  README.md
Labels: needs review

#766 Template search
  src/components/TemplateGallery/SearchBox.tsx
  src/components/TemplateGallery/SearchResults.tsx
Labels: needs review

#768 Syntax highlighting
  package-lock.json
  package.json
  src/components/Head.tsx
  src/components/Layout.tsx
  src/components/TemplateGallery/Snippet.tsx
  src/components/TemplateGallery/TemplatePage.tsx
  src/pages/404.tsx
  src/pages/index.tsx
  src/templates/markdownTemplate.tsx
Labels: needs review

#614 Alewis/wrangler multi route
  src/content/tooling/wrangler/commands.md
  src/content/tooling/wrangler/configuration/_index.md
  src/content/tooling/wrangler/configuration/environments.md
Labels: blocked, tooling

#606 Alewis/custom webpack config for sites
  src/content/tooling/wrangler/sites.md
  src/content/tooling/wrangler/webpack.md
Labels: guides

#732 Add about/metrics to the docs
  src/content/about/metrics.md
Labels: blocked

#765 add Wrangler Tail to commands documentation.
  workers-docs/src/content/tooling/wrangler/commands.md
Labels: blocked

#789 Updates dependencies to latest with `npm update`
  cloudflare-docs-theme/package.json
  cloudflare-docs-theme/src/templates/markdownTemplate.tsx
  package.json
  workers-docs/package.json
  workers-docs/workers-site/package-lock.json
  workers-docs/workers-site/package.json
  workers-docs/yarn.lock
  yarn.lock
Labels: needs review

#794 fix tutorial image refs
  workers-docs/src/content/tutorials/build-a-serverless-function/_index.md
  workers-docs/src/content/tutorials/hosting-static-wordpress-sites/_index.md
Labels: needs review

#816 Fix Tests with gatsby
  .github/workflows/main.yml
  workers-docs/workers-site/src/mocks.js
Labels: needs review

#710 Mention CF_ZONE_ID in environment variables
  workers-docs/src/content/tooling/wrangler/configuration/_index.md
Labels: merge-conflict

#726 add auth0 tutorial
  src/content/tutorials/user-auth-with-auth0/_index.md
  src/content/tutorials/user-auth-with-auth0/media/auth0-allowed-urls.png
  src/content/tutorials/user-auth-with-auth0/media/auth0-flow.png
  src/content/tutorials/user-auth-with-auth0/media/auth0-login.png
  src/content/tutorials/user-auth-with-auth0/media/auth0-settings.png
  src/content/tutorials/user-auth-with-auth0/media/creating-an-application.png
  src/content/tutorials/user-auth-with-auth0/media/example-vid.gif
  src/content/tutorials/user-auth-with-auth0/media/userInfo.png
  workers-docs/src/content/tutorials/_index.md
Labels: blocked

#799 Update initial definition of createTodo
  workers-docs/src/content/tutorials/build-a-todo-list/_index.md
Labels: needs review
