Repository cloudflare/workers-docs, pull requests merged in 2020-06, with the labels that each got.

#793 fix image src
  cloudflare-docs-theme/src/components/Link.tsx
Labels: needs review

#893 Update readme
  README.md
Labels: needs review

#892 Cleanup wrangler docs
  workers-docs/src/content/quickstart/_index.md
  workers-docs/src/content/tooling/wrangler/_index.md
  workers-docs/src/content/tooling/wrangler/commands.md
  workers-docs/src/content/tooling/wrangler/configuration.md
  workers-docs/src/content/tooling/wrangler/configuration/_index.md
  workers-docs/src/content/tooling/wrangler/environments.md
  workers-docs/src/content/tooling/wrangler/kv_commands.md
  workers-docs/src/content/tooling/wrangler/secrets.md
  workers-docs/src/content/tooling/wrangler/sites.md
  workers-docs/src/content/tooling/wrangler/webpack.md
  workers-docs/workers-site/redirects/newDocs.js
Labels: needs review

#905 Avery/rebased preview namespaces
  workers-docs/src/content/tooling/wrangler/commands.md
  workers-docs/src/content/tooling/wrangler/configuration.md
  workers-docs/src/content/tooling/wrangler/kv_commands.md
Labels: needs review, tooling

#903 document preview namespaces
  workers-docs/src/content/tooling/wrangler/commands.md
  workers-docs/src/content/tooling/wrangler/configuration.md
  workers-docs/src/content/tooling/wrangler/environments.md
  workers-docs/src/content/tooling/wrangler/kv_commands.md
  workers-docs/src/content/tutorials/build-a-jamstack-app/_index.md
  workers-docs/src/content/tutorials/user-auth-with-auth0/_index.md
Labels: needs review, typo
